Fix ppl

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -64,15 +64,15 @@ jobs:
           REGISTRY_USERNAME: ${{ secrets.DOCKERHUB_USER }}
           REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
           REGISTRY_HOST: registry.hub.docker.com
-          DOCKER_ORG: entando
+          DOCKER_ORG: pippo
         run: |
-          curl blabla
           docker login $REGISTRY_HOST -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD
           versionSuffix=$(echo "${{ github.event.pull_request.title }}" | awk '{print $1}')
           cd content
           bash ../.github/functions/utils.sh setBundleVersion -$versionSuffix
           ent --debug bundle pack --org $DOCKER_ORG --stdout
           ent --debug bundle publish
+          echo "Error code $?"
           version=$(bash ../.github/functions/utils.sh getBundleImage)
           echo "VERSION=$version" >> $GITHUB_OUTPUT
       - name: Publish artifact version
